In [2]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import Flatten
from tensorflow.keras.models import Sequential





In [3]:
reviews = ['nice food','amazing restaurants', 'too good','just loved it','will go again','horrible food','never go there',
          'poor service','poor quality','needs improvement']
sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [4]:
#function of one_hot
one_hot('good ambience',30)#The number varies from 0 to 30

[26, 18]

In [5]:
one_hot_size =30
encoded_reviews=[]
for d in reviews:
    encoded_reviews.append(one_hot(d,one_hot_size))
encoded_reviews  

[[15, 7],
 [18, 28],
 [10, 26],
 [25, 5, 19],
 [10, 10, 25],
 [8, 7],
 [23, 10, 24],
 [10, 21],
 [10, 3],
 [1, 16]]

In [6]:
#now some hot_encoded are of three sizes and some are four so we are gonna pad everything

In [8]:
length_padding = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=length_padding, padding='post')#post means pad the reviews at the end
print(padded_reviews)

[[15  7  0]
 [18 28  0]
 [10 26  0]
 [25  5 19]
 [10 10 25]
 [ 8  7  0]
 [23 10 24]
 [10 21  0]
 [10  3  0]
 [ 1 16  0]]


In [9]:
embeded_vector_size = 5 #embeded_vector_size means the size of the vector for each word
#first layer is embedding with some arguments
# second layer i flatten layer
# third layer is one neuron dense layer with sigmoid
# 1 one_hot_size 2 embeded_vector_size 3 lenght_padding 4 name for embedding layer
model = Sequential()
model.add(Embedding(one_hot_size, embeded_vector_size, input_length = length_padding, name="embeding" ))
model.add(Flatten())
model.add(Dense(1, activation = 'sigmoid'))

In [10]:
x = padded_reviews
y = sentiment

In [11]:
model.compile(optimizer = 'adam', loss='binary_crossentropy', metrics=['accuracy'])

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embeding (Embedding)        (None, 3, 5)              150       
                                                                 
 flatten (Flatten)           (None, 15)                0         
                                                                 
 dense (Dense)               (None, 1)                 16        
                                                                 
Total params: 166
Trainable params: 166
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.fit(x,y, epochs=50)

Epoch 1/50
1/1 [==============================] - 1s 958ms/step - loss: 0.6889 - accuracy: 0.6000
Epoch 2/50
1/1 [==============================] - 0s 16ms/step - loss: 0.6879 - accuracy: 0.7000
Epoch 3/50
1/1 [==============================] - 0s 0s/step - loss: 0.6869 - accuracy: 0.7000
Epoch 4/50
1/1 [==============================] - 0s 16ms/step - loss: 0.6859 - accuracy: 0.7000
Epoch 5/50
1/1 [==============================] - 0s 0s/step - loss: 0.6849 - accuracy: 0.7000
Epoch 6/50
1/1 [==============================] - 0s 16ms/step - loss: 0.6839 - accuracy: 0.7000
Epoch 7/50
1/1 [==============================] - 0s 0s/step - loss: 0.6829 - accuracy: 0.7000
Epoch 8/50
1/1 [==============================] - 0s 0s/step - loss: 0.6819 - accuracy: 0.7000
Epoch 9/50
1/1 [==============================] - 0s 16ms/step - loss: 0.6809 - accuracy: 0.7000
Epoch 10/50
1/1 [==============================] - 0s 0s/step - loss: 0.6799 - accuracy: 0.7000
Epoch 11/50
1/1 [=====================